### PR TITLE
chore: update java authentication examples w/use of builders

### PR DESCRIPTION
**Pull request by padamstx**

### CODE REVIEW

**Comment by mkistler** [comment]
Should we be concerned about removing the old form of authenticator construction?  I'm thinking of SDKs that may be using the old Java Core and thus don't have the new builder methods -- don't we need to preserve this information for users of those SDKs?

**Comment by padamstx** [comment]
> Should we be concerned about removing the old form of authenticator construction? I'm thinking of SDKs that may be using the old Java Core and thus don't have the new builder methods -- don't we need to preserve this information for users of those SDKs?

Yeah, i guess I didn't consider that scenario, but we should maintain both flavors, with perhaps some comments above each.   I'll make that change.

**Comment by padamstx** [comment]
@mkistler Ok, pushed the changes to include both the old and new examples.

**Review by mkistler — APPROVED** [review]
Looks good! 👍

**Pull request merged**
