### PR TITLE
Add Authentication with IBM Cloud starter kit applications section

### PR DESCRIPTION
**Pull request by mojito317**
Since it would be useful for all the generated SDKs, I initialized a section about authentication with IBM Cloud starter kit apps.

I also fixed one broken link.

### CODE REVIEW

**Comment by mkistler** [comment]
Thanks for the contribution but I wonder why we need a special section for authentication for starter apps.  Shouldn't starter apps use the standard authentication mechanisms in IBM Cloud?  And if that's the case, shouldn't our core SDKs already support those mechanisms?  If the latter is not true, then we should try to address that.  I'm not sure this is a problem we should try to solve with documentation.

**Comment by mojito317** [comment]
> Shouldn't starter apps use the standard authentication mechanisms in IBM Cloud?

The authentication mechanisms are strongly depending on the platform where the application is running on. E.g. Cloud Foundry apps are storing configurations in `VCAP_SERVICES` env vars, but Kubernetes has a JSON file or flat attributes for the same reason. _ibm-cloud-env_ libraries are developed for Cloud apps to have a portable solution between them, and the developer does not have to study how the platform works because the `mappings.json` file hides the layers underneath. So this is the _standard_ I have tried to write down in this PR. See https://cloud.ibm.com/docs/apps?topic=apps-credentials_overview.

> shouldn't our core SDKs already support those mechanisms

The usage of the `mappings.json` file via the `ibm-cloud-env` libraries is not supported in the core SDKs yet.

In the case of a Cloudant service, the `mappings.json` file must contain `cloudant_url`, `cloudant_apikey`, and other kinds of credentials with the `cloudant` prefix. I don’t have much insight into other services, but I think the key is this prefix. Then the core could check the env vars, the external config file, and the mappings.json file with the help of the `ibm-cloud-env` libraries as well to fetch the right credentials. Till this does not exist in the core, it would be nice to see this documented, and we found this documentation would be the best place for it instead to document it on our API Docs.

**Review by mkistler — APPROVED** [review]
Looks good! 👍

**Review by padamstx — COMMENTED** [review]
I'm having a hard time understanding the purpose of this PR.  Is it to document something that we do not yet support?

The SDK core libraries currently support configuration properties specified as:
1. properties defined in a "Java Properties"-like file, with a well-defined algorithm for finding this file
2. config properties exported as environment variables
3. configuration of CF-related apps/resources specified within an exported VCAP_SERVICES env var where the value contains a JSON object reflecting the config

It's not clear to me how this PR's changes fit in with our existing support.

**Comment by mojito317** [comment]
Since there's no agreement on this, I'm closing this PR.

**Pull request closed without merging**
