### PR TITLE
chore(documentation): Add SDK catalog

### PR DESCRIPTION
**Pull request by christiancompton**
This PR adds the publicly available SDKs that rely on the Common SDK to the README.  I obtained these SDKs using the [Node core dependency graph](https://github.com/IBM/node-sdk-core/network/dependents?dependent_type=PACKAGE).

### CODE REVIEW

**Review by padamstx — APPROVED** [review]
Changes look fine to me.   The only question that nags at me is whether or not this file is the "correct" place for a project catalog like this.  I'll add this question to the issue

**Comment by jorge-ibm** [comment]
Looks good, I think you missed vpc https://github.com/IBM/vpc-python-sdk

**Comment by jorge-ibm** [comment]
A couple of others one here: https://github.com/IBM/java-sdk-core/network/dependents

**Comment by christiancompton** [comment]
I have added the additional SDKs, with the exception of the CP4D ones([Node](https://github.com/IBM/cloudpakfordata-node-sdk), [Java](https://github.com/IBM/cloudpakfordata-java-sdk)), which are obviously not maintained.

**Pull request merged**
